// <auto-generated />
namespace EmployeeWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuickFixEmployeetable1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuickFixEmployeetable1));
        
        string IMigrationMetadata.Id
        {
            get { return "201710111400146_QuickFixEmployeetable1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
